/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionModel
 */
export interface TransactionModel {
    /**
     * 
     * @type {string}
     * @memberof TransactionModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionModel
     */
    creator: string;
    /**
     * 
     * @type {string}
     * @memberof TransactionModel
     */
    categoryName: string;
    /**
     * 
     * @type {Date}
     * @memberof TransactionModel
     */
    timestampUtc: Date;
    /**
     * 
     * @type {number}
     * @memberof TransactionModel
     */
    amount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionModel
     */
    notes: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof TransactionModel
     */
    isRefill: boolean;
}

/**
 * Check if a given object implements the TransactionModel interface.
 */
export function instanceOfTransactionModel(value: object): value is TransactionModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('creator' in value) || value['creator'] === undefined) return false;
    if (!('categoryName' in value) || value['categoryName'] === undefined) return false;
    if (!('timestampUtc' in value) || value['timestampUtc'] === undefined) return false;
    if (!('amount' in value) || value['amount'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('isRefill' in value) || value['isRefill'] === undefined) return false;
    return true;
}

export function TransactionModelFromJSON(json: any): TransactionModel {
    return TransactionModelFromJSONTyped(json, false);
}

export function TransactionModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'creator': json['creator'],
        'categoryName': json['categoryName'],
        'timestampUtc': (new Date(json['timestampUtc'])),
        'amount': json['amount'],
        'notes': json['notes'],
        'isRefill': json['isRefill'],
    };
}

export function TransactionModelToJSON(json: any): TransactionModel {
    return TransactionModelToJSONTyped(json, false);
}

export function TransactionModelToJSONTyped(value?: TransactionModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'creator': value['creator'],
        'categoryName': value['categoryName'],
        'timestampUtc': ((value['timestampUtc']).toISOString()),
        'amount': value['amount'],
        'notes': value['notes'],
        'isRefill': value['isRefill'],
    };
}

