version: '3.8'
services:
  schmeconomics-api:
    build:
      context: ..
      dockerfile: compose/Dockerfile.api
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
    volumes:
      - db:/app/db/
    # No need for command since we're using ENTRYPOINT in Dockerfile

  schmeconomics-client:
    build:
      context: ..
      dockerfile: compose/Dockerfile.client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    env_file:
      - .env
    depends_on:
      - schmeconomics-api
    #volumes:
      #- ./schmeconomics.client:/app/schmeconomics.client
volumes:
  db: 
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: ${DATABASE_PATH}
  