FROM node:22-alpine AS builder

WORKDIR /app

# Copy package files
COPY schmeconomics.client/package*.json ./

# Install dependencies
RUN npm ci

# Copy client application
COPY schmeconomics.client/ .

# Build the Nuxt application
RUN npm run build

FROM node:22-alpine AS runner
WORKDIR /app
ARG CLIENT_PORT

COPY --from=builder /app/.output ./.output

ENV NODE_ENV=production

# Expose port
EXPOSE ${CLIENT_PORT}

# Start the application
CMD ["node", ".output/server/index.mjs"]
