/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserModel } from './UserModel';
import {
    UserModelFromJSON,
    UserModelFromJSONTyped,
    UserModelToJSON,
    UserModelToJSONTyped,
} from './UserModel';
import type { CategoryModel } from './CategoryModel';
import {
    CategoryModelFromJSON,
    CategoryModelFromJSONTyped,
    CategoryModelToJSON,
    CategoryModelToJSONTyped,
} from './CategoryModel';

/**
 * 
 * @export
 * @interface AccountModel
 */
export interface AccountModel {
    /**
     * 
     * @type {string}
     * @memberof AccountModel
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof AccountModel
     */
    name: string;
    /**
     * 
     * @type {Array<CategoryModel>}
     * @memberof AccountModel
     */
    categories: Array<CategoryModel>;
    /**
     * 
     * @type {Array<UserModel>}
     * @memberof AccountModel
     */
    users: Array<UserModel>;
}

/**
 * Check if a given object implements the AccountModel interface.
 */
export function instanceOfAccountModel(value: object): value is AccountModel {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('categories' in value) || value['categories'] === undefined) return false;
    if (!('users' in value) || value['users'] === undefined) return false;
    return true;
}

export function AccountModelFromJSON(json: any): AccountModel {
    return AccountModelFromJSONTyped(json, false);
}

export function AccountModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccountModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'categories': ((json['categories'] as Array<any>).map(CategoryModelFromJSON)),
        'users': ((json['users'] as Array<any>).map(UserModelFromJSON)),
    };
}

export function AccountModelToJSON(json: any): AccountModel {
    return AccountModelToJSONTyped(json, false);
}

export function AccountModelToJSONTyped(value?: AccountModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'categories': ((value['categories'] as Array<any>).map(CategoryModelToJSON)),
        'users': ((value['users'] as Array<any>).map(UserModelToJSON)),
    };
}

