/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthModel
 */
export interface AuthModel {
    /**
     * 
     * @type {string}
     * @memberof AuthModel
     */
    accessToken: string;
    /**
     * 
     * @type {string}
     * @memberof AuthModel
     */
    refreshToken: string;
    /**
     * 
     * @type {Date}
     * @memberof AuthModel
     */
    expiresOnUtc: Date;
}

/**
 * Check if a given object implements the AuthModel interface.
 */
export function instanceOfAuthModel(value: object): value is AuthModel {
    if (!('accessToken' in value) || value['accessToken'] === undefined) return false;
    if (!('refreshToken' in value) || value['refreshToken'] === undefined) return false;
    if (!('expiresOnUtc' in value) || value['expiresOnUtc'] === undefined) return false;
    return true;
}

export function AuthModelFromJSON(json: any): AuthModel {
    return AuthModelFromJSONTyped(json, false);
}

export function AuthModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthModel {
    if (json == null) {
        return json;
    }
    return {
        
        'accessToken': json['accessToken'],
        'refreshToken': json['refreshToken'],
        'expiresOnUtc': (new Date(json['expiresOnUtc'])),
    };
}

export function AuthModelToJSON(json: any): AuthModel {
    return AuthModelToJSONTyped(json, false);
}

export function AuthModelToJSONTyped(value?: AuthModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessToken': value['accessToken'],
        'refreshToken': value['refreshToken'],
        'expiresOnUtc': ((value['expiresOnUtc']).toISOString()),
    };
}

