/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AccountModel,
  ToggleUserToAccountRequest,
  UpdateAccountRequest,
} from '../models/index';
import {
    AccountModelFromJSON,
    AccountModelToJSON,
    ToggleUserToAccountRequestFromJSON,
    ToggleUserToAccountRequestToJSON,
    UpdateAccountRequestFromJSON,
    UpdateAccountRequestToJSON,
} from '../models/index';

export interface ApiV1AccountCreatePostRequest {
    name?: string;
}

export interface ApiV1AccountDeleteIdDeleteRequest {
    id: string;
}

export interface ApiV1AccountToggleUserPostRequest {
    toggleUserToAccountRequest: ToggleUserToAccountRequest;
}

export interface ApiV1AccountUpdateIdPutRequest {
    id: string;
    updateAccountRequest: UpdateAccountRequest;
}

/**
 * 
 */
export class AccountApi extends runtime.BaseAPI {

    /**
     */
    async apiV1AccountAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AccountModel>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Account/All`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AccountModelFromJSON));
    }

    /**
     */
    async apiV1AccountAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AccountModel>> {
        const response = await this.apiV1AccountAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1AccountCreatePostRaw(requestParameters: ApiV1AccountCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountModel>> {
        const queryParameters: any = {};

        if (requestParameters['name'] != null) {
            queryParameters['name'] = requestParameters['name'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Account/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountModelFromJSON(jsonValue));
    }

    /**
     */
    async apiV1AccountCreatePost(requestParameters: ApiV1AccountCreatePostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountModel> {
        const response = await this.apiV1AccountCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1AccountDeleteIdDeleteRaw(requestParameters: ApiV1AccountDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1AccountDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Account/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1AccountDeleteIdDelete(requestParameters: ApiV1AccountDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AccountDeleteIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1AccountToggleUserPostRaw(requestParameters: ApiV1AccountToggleUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['toggleUserToAccountRequest'] == null) {
            throw new runtime.RequiredError(
                'toggleUserToAccountRequest',
                'Required parameter "toggleUserToAccountRequest" was null or undefined when calling apiV1AccountToggleUserPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/Account/ToggleUser`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ToggleUserToAccountRequestToJSON(requestParameters['toggleUserToAccountRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1AccountToggleUserPost(requestParameters: ApiV1AccountToggleUserPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1AccountToggleUserPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1AccountUpdateIdPutRaw(requestParameters: ApiV1AccountUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccountModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1AccountUpdateIdPut().'
            );
        }

        if (requestParameters['updateAccountRequest'] == null) {
            throw new runtime.RequiredError(
                'updateAccountRequest',
                'Required parameter "updateAccountRequest" was null or undefined when calling apiV1AccountUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/Account/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateAccountRequestToJSON(requestParameters['updateAccountRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccountModelFromJSON(jsonValue));
    }

    /**
     */
    async apiV1AccountUpdateIdPut(requestParameters: ApiV1AccountUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccountModel> {
        const response = await this.apiV1AccountUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
