/* tslint:disable */
/* eslint-disable */
/**
 * Schmeconomics.Api | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CategoryModel,
  CreateCategoryRequest,
  UpdateCategoriesOrderRequest,
  UpdateCategoriesRefillValueRequest,
  UpdateCategoryRequest,
} from '../models/index';
import {
    CategoryModelFromJSON,
    CategoryModelToJSON,
    CreateCategoryRequestFromJSON,
    CreateCategoryRequestToJSON,
    UpdateCategoriesOrderRequestFromJSON,
    UpdateCategoriesOrderRequestToJSON,
    UpdateCategoriesRefillValueRequestFromJSON,
    UpdateCategoriesRefillValueRequestToJSON,
    UpdateCategoryRequestFromJSON,
    UpdateCategoryRequestToJSON,
} from '../models/index';

export interface ApiV1CategoryCreatePostRequest {
    createCategoryRequest: CreateCategoryRequest;
}

export interface ApiV1CategoryDeleteIdDeleteRequest {
    id: string;
}

export interface ApiV1CategoryForAccountAccountIdGetRequest {
    accountId: string;
}

export interface ApiV1CategoryRefillAccountIdPostRequest {
    accountId: string;
}

export interface ApiV1CategoryUpdateIdPutRequest {
    id: string;
    updateCategoryRequest: UpdateCategoryRequest;
}

export interface ApiV1CategoryUpdateOrderPutRequest {
    updateCategoriesOrderRequest: UpdateCategoriesOrderRequest;
}

export interface ApiV1CategoryUpdateRefillValuesPutRequest {
    updateCategoriesRefillValueRequest: UpdateCategoriesRefillValueRequest;
}

/**
 * 
 */
export class CategoryApi extends runtime.BaseAPI {

    /**
     */
    async apiV1CategoryCreatePostRaw(requestParameters: ApiV1CategoryCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryModel>> {
        if (requestParameters['createCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'createCategoryRequest',
                'Required parameter "createCategoryRequest" was null or undefined when calling apiV1CategoryCreatePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/Category/Create`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCategoryRequestToJSON(requestParameters['createCategoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryModelFromJSON(jsonValue));
    }

    /**
     */
    async apiV1CategoryCreatePost(requestParameters: ApiV1CategoryCreatePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryModel> {
        const response = await this.apiV1CategoryCreatePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1CategoryDeleteIdDeleteRaw(requestParameters: ApiV1CategoryDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1CategoryDeleteIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Category/Delete/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1CategoryDeleteIdDelete(requestParameters: ApiV1CategoryDeleteIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1CategoryDeleteIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1CategoryForAccountAccountIdGetRaw(requestParameters: ApiV1CategoryForAccountAccountIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryModel>>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling apiV1CategoryForAccountAccountIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Category/ForAccount/{accountId}`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryModelFromJSON));
    }

    /**
     */
    async apiV1CategoryForAccountAccountIdGet(requestParameters: ApiV1CategoryForAccountAccountIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryModel>> {
        const response = await this.apiV1CategoryForAccountAccountIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1CategoryRefillAccountIdPostRaw(requestParameters: ApiV1CategoryRefillAccountIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling apiV1CategoryRefillAccountIdPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/Category/Refill/{accountId}`;
        urlPath = urlPath.replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1CategoryRefillAccountIdPost(requestParameters: ApiV1CategoryRefillAccountIdPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1CategoryRefillAccountIdPostRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1CategoryUpdateIdPutRaw(requestParameters: ApiV1CategoryUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CategoryModel>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1CategoryUpdateIdPut().'
            );
        }

        if (requestParameters['updateCategoryRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCategoryRequest',
                'Required parameter "updateCategoryRequest" was null or undefined when calling apiV1CategoryUpdateIdPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/Category/Update/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCategoryRequestToJSON(requestParameters['updateCategoryRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CategoryModelFromJSON(jsonValue));
    }

    /**
     */
    async apiV1CategoryUpdateIdPut(requestParameters: ApiV1CategoryUpdateIdPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CategoryModel> {
        const response = await this.apiV1CategoryUpdateIdPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1CategoryUpdateOrderPutRaw(requestParameters: ApiV1CategoryUpdateOrderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryModel>>> {
        if (requestParameters['updateCategoriesOrderRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCategoriesOrderRequest',
                'Required parameter "updateCategoriesOrderRequest" was null or undefined when calling apiV1CategoryUpdateOrderPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/Category/UpdateOrder`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCategoriesOrderRequestToJSON(requestParameters['updateCategoriesOrderRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryModelFromJSON));
    }

    /**
     */
    async apiV1CategoryUpdateOrderPut(requestParameters: ApiV1CategoryUpdateOrderPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryModel>> {
        const response = await this.apiV1CategoryUpdateOrderPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1CategoryUpdateRefillValuesPutRaw(requestParameters: ApiV1CategoryUpdateRefillValuesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CategoryModel>>> {
        if (requestParameters['updateCategoriesRefillValueRequest'] == null) {
            throw new runtime.RequiredError(
                'updateCategoriesRefillValueRequest',
                'Required parameter "updateCategoriesRefillValueRequest" was null or undefined when calling apiV1CategoryUpdateRefillValuesPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/Category/UpdateRefillValues`;

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCategoriesRefillValueRequestToJSON(requestParameters['updateCategoriesRefillValueRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CategoryModelFromJSON));
    }

    /**
     */
    async apiV1CategoryUpdateRefillValuesPut(requestParameters: ApiV1CategoryUpdateRefillValuesPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CategoryModel>> {
        const response = await this.apiV1CategoryUpdateRefillValuesPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
